 let markets = [
        {
          "FMID": 1018261,
          "FMID__1": "Caledonia Farmers Market Association - Danville",
          "FMID__2": "https://sites.google.com/site/caledoniafarmersmarket/",
          "FMID__3": "https://www.facebook.com/Danville.VT.Farmers.Market/",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "Danville",
          "FMID__9": "Caledonia",
          "FMID__10": "Vermont",
          "FMID__11": 5828,
          "FMID__12": "06/14/2017 to 08/30/2017",
          "FMID__13": "Wed: 9:00 AM-1:00 PM;",
          "FMID__14": "09/06/2017 to 10/18/2017",
          "FMID__15": "Wed: 2:00 PM-6:00 PM;",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -72.140337,
          "FMID__21": 44.411036,
          "Location": "",
          "Credit": "Y",
          "WIC": "Y",
          "WICcash": "N",
          "SFMNP": "Y",
          "SNAP": "N",
          "Organic": "Y",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "Y",
          "Flowers": "Y",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "Y",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "Y",
          "Prepared": "Y",
          "Soap": "Y",
          "Trees": "Y",
          "Wine": "N",
          "Coffee": "Y",
          "Beans": "Y",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "Y",
          "PetFood": "Y",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1018318,
          "FMID__1": "Stearns Homestead Farmers' Market",
          "FMID__2": "http://www.StearnsHomestead.com",
          "FMID__3": "StearnsHomesteadFarmersMarket",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "6975 Ridge Road",
          "FMID__8": "Parma",
          "FMID__9": "Cuyahoga",
          "FMID__10": "Ohio",
          "FMID__11": "",
          "FMID__12": "06/24/2017 to 09/30/2017",
          "FMID__13": "Sat: 9:00 AM-1:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -81.7339387,
          "FMID__21": 41.3748009,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "Y",
          "SNAP": "N",
          "Organic": "-",
          "Bakedgoods": "Y",
          "Cheese": "N",
          "Crafts": "Y",
          "Flowers": "Y",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "Y",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "Y",
          "Prepared": "N",
          "Soap": "Y",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1009364,
          "FMID__1": "106 S. Main Street Farmers Market",
          "FMID__2": "http://thetownofsixmile.wordpress.com/",
          "FMID__3": "",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "106 S. Main Street",
          "FMID__8": "Six Mile",
          "FMID__9": "",
          "FMID__10": "South Carolina",
          "FMID__11": 29682,
          "FMID__12": "",
          "FMID__13": "",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -82.8187,
          "FMID__21": 34.8042,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "N",
          "SNAP": "N",
          "Organic": "-",
          "Bakedgoods": "",
          "Cheese": "",
          "Crafts": "",
          "Flowers": "",
          "Eggs": "",
          "Seafood": "",
          "Herbs": "",
          "Vegetables": "",
          "Honey": "",
          "Jams": "",
          "Maple": "",
          "Meat": "",
          "Nursery": "",
          "Nuts": "",
          "Plants": "",
          "Poultry": "",
          "Prepared": "",
          "Soap": "",
          "Trees": "",
          "Wine": "",
          "Coffee": "",
          "Beans": "",
          "Fruits": "",
          "Grains": "",
          "Juices": "",
          "Mushrooms": "",
          "PetFood": "",
          "Tofu": "",
          "WildHarvested": ""
        },
        {
          "FMID": 1010691,
          "FMID__1": "10th Steet Community Farmers Market",
          "FMID__2": "",
          "FMID__3": "",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "http://agrimissouri.com/mo-grown/grodetail.php?type=mo-grown&ID=275",
          "FMID__7": "10th Street and Poplar",
          "FMID__8": "Lamar",
          "FMID__9": "Barton",
          "FMID__10": "Missouri",
          "FMID__11": 64759,
          "FMID__12": "04/02/2014 to 11/30/2014",
          "FMID__13": "Wed: 3:00 PM-6:00 PM;Sat: 8:00 AM-1:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -94.2746191,
          "FMID__21": 37.495628,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "N",
          "SNAP": "N",
          "Organic": "-",
          "Bakedgoods": "Y",
          "Cheese": "N",
          "Crafts": "Y",
          "Flowers": "N",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "Y",
          "Poultry": "Y",
          "Prepared": "Y",
          "Soap": "Y",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1002454,
          "FMID__1": "112st Madison Avenue",
          "FMID__2": "",
          "FMID__3": "",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "112th Madison Avenue",
          "FMID__8": "New York",
          "FMID__9": "New York",
          "FMID__10": "New York",
          "FMID__11": 10029,
          "FMID__12": "July to November",
          "FMID__13": "Tue:8:00 am - 5:00 pm;Sat:8:00 am - 8:00 pm;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -73.9493,
          "FMID__21": 40.7939,
          "Location": "Private business parking lot",
          "Credit": "N",
          "WIC": "N",
          "WICcash": "Y",
          "SFMNP": "Y",
          "SNAP": "N",
          "Organic": "-",
          "Bakedgoods": "Y",
          "Cheese": "N",
          "Crafts": "Y",
          "Flowers": "Y",
          "Eggs": "N",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "Y",
          "Plants": "N",
          "Poultry": "N",
          "Prepared": "Y",
          "Soap": "Y",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "N",
          "Fruits": "N",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1011100,
          "FMID__1": "12 South Farmers Market",
          "FMID__2": "http://www.12southfarmersmarket.com",
          "FMID__3": "12_South_Farmers_Market",
          "FMID__4": "@12southfrmsmkt",
          "FMID__5": "",
          "FMID__6": "@12southfrmsmkt",
          "FMID__7": "3000 Granny White Pike",
          "FMID__8": "Nashville",
          "FMID__9": "Davidson",
          "FMID__10": "Tennessee",
          "FMID__11": 37204,
          "FMID__12": "05/05/2015 to 10/27/2015",
          "FMID__13": "Tue: 3:30 PM-6:30 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -86.790709,
          "FMID__21": 36.11837,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "N",
          "SNAP": "Y",
          "Organic": "Y",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "N",
          "Flowers": "Y",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "Y",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "Y",
          "Prepared": "Y",
          "Soap": "Y",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "Y",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "Y",
          "Mushrooms": "Y",
          "PetFood": "Y",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1009845,
          "FMID__1": "125th Street Fresh Connect Farmers' Market",
          "FMID__2": "http://www.125thStreetFarmersMarket.com",
          "FMID__3": "https://www.facebook.com/125thStreetFarmersMarket",
          "FMID__4": "https://twitter.com/FarmMarket125th",
          "FMID__5": "",
          "FMID__6": "Instagram--> 125thStreetFarmersMarket",
          "FMID__7": "163 West 125th Street and Adam Clayton Powell, Jr. Blvd.",
          "FMID__8": "New York",
          "FMID__9": "New York",
          "FMID__10": "New York",
          "FMID__11": 10027,
          "FMID__12": "06/10/2014 to 11/25/2014",
          "FMID__13": "Tue: 10:00 AM-7:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -73.9482477,
          "FMID__21": 40.8089533,
          "Location": "Federal/State government building grounds",
          "Credit": "Y",
          "WIC": "Y",
          "WICcash": "N",
          "SFMNP": "Y",
          "SNAP": "Y",
          "Organic": "Y",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "Y",
          "Flowers": "Y",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "Y",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "Y",
          "Plants": "N",
          "Poultry": "Y",
          "Prepared": "Y",
          "Soap": "Y",
          "Trees": "N",
          "Wine": "Y",
          "Coffee": "Y",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "Y",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1005586,
          "FMID__1": "12th & Brandywine Urban Farm Market",
          "FMID__2": "",
          "FMID__3": "https://www.facebook.com/pages/12th-Brandywine-Urban-Farm-Community-Garden/253769448091860",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "https://www.facebook.com/delawareurbanfarmcoalition",
          "FMID__7": "12th & Brandywine Streets",
          "FMID__8": "Wilmington",
          "FMID__9": "New Castle",
          "FMID__10": "Delaware",
          "FMID__11": 19801,
          "FMID__12": "05/16/2014 to 10/17/2014",
          "FMID__13": "Fri: 8:00 AM-11:00 AM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -75.53446,
          "FMID__21": 39.742117,
          "Location": "On a farm from: a barn, a greenhouse, a tent, a stand, etc",
          "Credit": "N",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "N",
          "SNAP": "Y",
          "Organic": "N",
          "Bakedgoods": "N",
          "Cheese": "N",
          "Crafts": "N",
          "Flowers": "N",
          "Eggs": "N",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "N",
          "Jams": "N",
          "Maple": "N",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "N",
          "Prepared": "N",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1008071,
          "FMID__1": "14&U Farmers' Market",
          "FMID__2": "",
          "FMID__3": "https://www.facebook.com/14UFarmersMarket",
          "FMID__4": "https://twitter.com/14UFarmersMkt",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "1400 U Street NW",
          "FMID__8": "Washington",
          "FMID__9": "District of Columbia",
          "FMID__10": "District of Columbia",
          "FMID__11": 20009,
          "FMID__12": "05/03/2014 to 11/22/2014",
          "FMID__13": "Sat: 9:00 AM-1:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -77.0320505,
          "FMID__21": 38.9169984,
          "Location": "Other",
          "Credit": "Y",
          "WIC": "Y",
          "WICcash": "Y",
          "SFMNP": "Y",
          "SNAP": "Y",
          "Organic": "Y",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "N",
          "Flowers": "Y",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "Y",
          "Plants": "Y",
          "Poultry": "Y",
          "Prepared": "N",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "Y",
          "Fruits": "Y",
          "Grains": "Y",
          "Juices": "Y",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1012710,
          "FMID__1": "14th & Kennedy Street Farmers Market",
          "FMID__2": "",
          "FMID__3": "https://www.facebook.com/14KennnedyFarmersMarket/",
          "FMID__4": "14KenFM",
          "FMID__5": "",
          "FMID__6": "instagram:14kenfm",
          "FMID__7": "5500 Colorado Avenue, NW",
          "FMID__8": "Washington",
          "FMID__9": "District of Columbia",
          "FMID__10": "District of Columbia",
          "FMID__11": 20011,
          "FMID__12": "04/09/2016 to 11/19/2016",
          "FMID__13": "Sat: 9:00 AM-1:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -77.0334486,
          "FMID__21": 38.9559783,
          "Location": "",
          "Credit": "Y",
          "WIC": "Y",
          "WICcash": "Y",
          "SFMNP": "Y",
          "SNAP": "Y",
          "Organic": "N",
          "Bakedgoods": "Y",
          "Cheese": "N",
          "Crafts": "Y",
          "Flowers": "Y",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "Y",
          "Prepared": "Y",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "Y",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "Y",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1019157,
          "FMID__1": "16th Ave Farmers Market",
          "FMID__2": "http://16thavefarmersmarket.com",
          "FMID__3": "",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "NE 16th Ave & Broadway",
          "FMID__8": "Portland",
          "FMID__9": "Multnomah",
          "FMID__10": "Oregon",
          "FMID__11": 97212,
          "FMID__12": "06/03/2018 to 10/28/2018",
          "FMID__13": "Sun: 9:00 AM-1:30 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -122.649446,
          "FMID__21": 45.534498,
          "Location": "",
          "Credit": "Y",
          "WIC": "Y",
          "WICcash": "Y",
          "SFMNP": "Y",
          "SNAP": "N",
          "Organic": "-",
          "Bakedgoods": "Y",
          "Cheese": "N",
          "Crafts": "Y",
          "Flowers": "Y",
          "Eggs": "N",
          "Seafood": "N",
          "Herbs": "N",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "Y",
          "Poultry": "N",
          "Prepared": "Y",
          "Soap": "Y",
          "Trees": "Y",
          "Wine": "N",
          "Coffee": "Y",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "Y"
        },
        {
          "FMID": 1018792,
          "FMID__1": "170 Farm Stand",
          "FMID__2": "",
          "FMID__3": "https://www.facebook.com/CommunityFoodAction/",
          "FMID__4": "https://twitter.com/GoodEatsBX",
          "FMID__5": "https://www.youtube.com/channel/UCZnt7sSNKIBrn2rMy1RyE_w",
          "FMID__6": "https://www.instagram.com/goodeatsbx/",
          "FMID__7": "NE Corner of 170th St. & Townsend Avenue",
          "FMID__8": "Bronx",
          "FMID__9": "Bronx",
          "FMID__10": "New York",
          "FMID__11": 10452,
          "FMID__12": "07/05/2017 to 11/22/2017",
          "FMID__13": "Wed: 2:30 PM-6:30 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -73.9167841,
          "FMID__21": 40.8398843,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "Y",
          "SFMNP": "Y",
          "SNAP": "Y",
          "Organic": "-",
          "Bakedgoods": "N",
          "Cheese": "N",
          "Crafts": "N",
          "Flowers": "N",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "N",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "N",
          "Maple": "N",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "N",
          "Prepared": "N",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "Y",
          "Fruits": "Y",
          "Grains": "Y",
          "Juices": "N",
          "Mushrooms": "Y",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1016782,
          "FMID__1": "175th Street Greenmarket",
          "FMID__2": "https://www.grownyc.org/greenmarket/manhattan/175th-street",
          "FMID__3": "https://www.facebook.com/ManhattanGreenmarkets/",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "175th Street between Wadsworth & Broadway",
          "FMID__8": "New York",
          "FMID__9": "New York",
          "FMID__10": "New York",
          "FMID__11": 10033,
          "FMID__12": "06/29/2017 to 11/22/2017",
          "FMID__13": "Tue: 8:00 AM-6:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -73.938049,
          "FMID__21": 40.846354,
          "Location": "",
          "Credit": "Y",
          "WIC": "Y",
          "WICcash": "Y",
          "SFMNP": "Y",
          "SNAP": "Y",
          "Organic": "N",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "N",
          "Flowers": "Y",
          "Eggs": "Y",
          "Seafood": "Y",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "N",
          "Prepared": "N",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "Y",
          "Juices": "Y",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1003877,
          "FMID__1": "17th Ave Market",
          "FMID__2": "http://www.iatp.org/minimarkets",
          "FMID__3": "",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "1622 6th St NE",
          "FMID__8": "Minneapolis",
          "FMID__9": "Hennepin",
          "FMID__10": "Minnesota",
          "FMID__11": 55413,
          "FMID__12": "June to September",
          "FMID__13": "Wed:3:00 pm - 7:00 pm;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -93.2591,
          "FMID__21": 45.0044,
          "Location": "Faith-based institution (e.g., church, mosque, synagogue, temple)",
          "Credit": "N",
          "WIC": "Y",
          "WICcash": "Y",
          "SFMNP": "Y",
          "SNAP": "N",
          "Organic": "-",
          "Bakedgoods": "N",
          "Cheese": "N",
          "Crafts": "N",
          "Flowers": "N",
          "Eggs": "N",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "N",
          "Honey": "N",
          "Jams": "N",
          "Maple": "N",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "N",
          "Prepared": "N",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "N",
          "Fruits": "N",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1016784,
          "FMID__1": "17th Street Farmers Market",
          "FMID__2": "http://enrichmond.org",
          "FMID__3": "https://www.facebook.com/17thStreetFarmersMarket/",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "100 North 17th St.",
          "FMID__8": "Richmond",
          "FMID__9": "Richmond City",
          "FMID__10": "Virginia",
          "FMID__11": 23219,
          "FMID__12": "06/08/2017 to",
          "FMID__13": "Thu: 3:00 PM-6:30 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -77.428364,
          "FMID__21": 37.53385,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "N",
          "SNAP": "Y",
          "Organic": "-",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "N",
          "Flowers": "N",
          "Eggs": "Y",
          "Seafood": "Y",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "Y",
          "Prepared": "N",
          "Soap": "Y",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "Y",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "Y",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1010968,
          "FMID__1": "18th and Christian Farmers' Market",
          "FMID__2": "http://thefoodtrust.org/farmers-markets/market/18th-Christian",
          "FMID__3": "",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "18th Street and Christian Street",
          "FMID__8": "Philadelphia",
          "FMID__9": "Philadelphia",
          "FMID__10": "Pennsylvania",
          "FMID__11": 19146,
          "FMID__12": "06/01/2015 to 11/15/2015",
          "FMID__13": "Thu: 3:00 PM-7:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -75.173431,
          "FMID__21": 39.940943,
          "Location": "",
          "Credit": "Y",
          "WIC": "Y",
          "WICcash": "N",
          "SFMNP": "Y",
          "SNAP": "Y",
          "Organic": "N",
          "Bakedgoods": "N",
          "Cheese": "N",
          "Crafts": "N",
          "Flowers": "N",
          "Eggs": "N",
          "Seafood": "N",
          "Herbs": "N",
          "Vegetables": "Y",
          "Honey": "N",
          "Jams": "N",
          "Maple": "N",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "N",
          "Prepared": "N",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1009994,
          "FMID__1": "18th Street Farmer's Market",
          "FMID__2": "",
          "FMID__3": "https://www.facebook.com/ScottsbluffFarmersMarket",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "18th and Broadway",
          "FMID__8": "Scottsbluff",
          "FMID__9": "Scotts Bluff",
          "FMID__10": "Nebraska",
          "FMID__11": 69361,
          "FMID__12": "06/07/2014 to 09/27/2014",
          "FMID__13": "Sat: 8:00 AM-11:00 AM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -103.662538,
          "FMID__21": 41.864268,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "N",
          "SNAP": "N",
          "Organic": "Y",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "Y",
          "Flowers": "Y",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "N",
          "Maple": "N",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "Y",
          "Poultry": "Y",
          "Prepared": "Y",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "Y",
          "Beans": "Y",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1018365,
          "FMID__1": "18th Street Farmers Market",
          "FMID__2": "",
          "FMID__3": "18th Street Farmers Market",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "825 18th Street",
          "FMID__8": "Charleston",
          "FMID__9": "Coles",
          "FMID__10": "Illinois",
          "FMID__11": 61920,
          "FMID__12": "05/20/2017 to 09/30/2017",
          "FMID__13": "Sat: 8:00 AM-12:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -88.1622392,
          "FMID__21": 39.4907144,
          "Location": "",
          "Credit": "Y",
          "WIC": "Y",
          "WICcash": "N",
          "SFMNP": "Y",
          "SNAP": "Y",
          "Organic": "-",
          "Bakedgoods": "Y",
          "Cheese": "N",
          "Crafts": "Y",
          "Flowers": "Y",
          "Eggs": "N",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "Y",
          "Poultry": "N",
          "Prepared": "N",
          "Soap": "Y",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1012790,
          "FMID__1": "19/27 Community Farmers Market",
          "FMID__2": "",
          "FMID__3": "https://www.facebook.com/1927-Community-Farmers-Market-1505265436358960/",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "NE 7th Ave",
          "FMID__8": "Chiefland",
          "FMID__9": "Levy",
          "FMID__10": "Florida",
          "FMID__11": 32626,
          "FMID__12": "09/03/2016 to 06/24/2017",
          "FMID__13": "Sat: 8:30 AM-1:00 PM;",
          "FMID__14": "09/02/2017 to 06/30/2018",
          "FMID__15": "Sat: 8:30 AM-1:00 PM;",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -82.8578732,
          "FMID__21": 29.4848541,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "N",
          "SNAP": "N",
          "Organic": "-",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "Y",
          "Flowers": "N",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "Y",
          "Poultry": "Y",
          "Prepared": "Y",
          "Soap": "Y",
          "Trees": "Y",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "Y",
          "Fruits": "Y",
          "Grains": "Y",
          "Juices": "N",
          "Mushrooms": "Y",
          "PetFood": "Y",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1012158,
          "FMID__1": "21 Acres Farm Market",
          "FMID__2": "http://21acres.org",
          "FMID__3": "https://www.facebook.com/21Acres/",
          "FMID__4": "@21acres",
          "FMID__5": "21AcresCenter's channel",
          "FMID__6": "Instagram @21acres",
          "FMID__7": "13701 NE 171st Street",
          "FMID__8": "Woodinville",
          "FMID__9": "King",
          "FMID__10": "Washington",
          "FMID__11": 98072,
          "FMID__12": "01/01/2016 to 12/31/2016",
          "FMID__13": "Wed: 11:00 AM-6:00 PM;Thu: 11:00 AM-6:00 PM;Fri: 11:00 AM-6:00 PM;Sat: 11:00 AM-6:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -122.1569875,
          "FMID__21": 47.7502397,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "N",
          "SNAP": "Y",
          "Organic": "Y",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "N",
          "Flowers": "N",
          "Eggs": "Y",
          "Seafood": "Y",
          "Herbs": "Y",
          "Vegetables": "N",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "Y",
          "Plants": "N",
          "Poultry": "Y",
          "Prepared": "Y",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "Y",
          "Beans": "Y",
          "Fruits": "Y",
          "Grains": "Y",
          "Juices": "Y",
          "Mushrooms": "Y",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        }
      ]
 