 let markets = [
        {
          "FMID": 1018261,
          "FMID__1": "Caledonia Farmers Market Association - Danville",
          "FMID__2": "https://sites.google.com/site/caledoniafarmersmarket/",
          "FMID__3": "https://www.facebook.com/Danville.VT.Farmers.Market/",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "Danville",
          "FMID__9": "Caledonia",
          "FMID__10": "Vermont",
          "FMID__11": 5828,
          "FMID__12": "06/14/2017 to 08/30/2017",
          "FMID__13": "Wed: 9:00 AM-1:00 PM;",
          "FMID__14": "09/06/2017 to 10/18/2017",
          "FMID__15": "Wed: 2:00 PM-6:00 PM;",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -72.140337,
          "FMID__21": 44.411036,
          "Location": "",
          "Credit": "Y",
          "WIC": "Y",
          "WICcash": "N",
          "SFMNP": "Y",
          "SNAP": "N",
          "Organic": "Y",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "Y",
          "Flowers": "Y",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "Y",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "Y",
          "Prepared": "Y",
          "Soap": "Y",
          "Trees": "Y",
          "Wine": "N",
          "Coffee": "Y",
          "Beans": "Y",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "Y",
          "PetFood": "Y",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1018318,
          "FMID__1": "Stearns Homestead Farmers' Market",
          "FMID__2": "http://www.StearnsHomestead.com",
          "FMID__3": "StearnsHomesteadFarmersMarket",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "6975 Ridge Road",
          "FMID__8": "Parma",
          "FMID__9": "Cuyahoga",
          "FMID__10": "Ohio",
          "FMID__11": "",
          "FMID__12": "06/24/2017 to 09/30/2017",
          "FMID__13": "Sat: 9:00 AM-1:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -81.7339387,
          "FMID__21": 41.3748009,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "Y",
          "SNAP": "N",
          "Organic": "-",
          "Bakedgoods": "Y",
          "Cheese": "N",
          "Crafts": "Y",
          "Flowers": "Y",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "Y",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "Y",
          "Prepared": "N",
          "Soap": "Y",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1009364,
          "FMID__1": "106 S. Main Street Farmers Market",
          "FMID__2": "http://thetownofsixmile.wordpress.com/",
          "FMID__3": "",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "106 S. Main Street",
          "FMID__8": "Six Mile",
          "FMID__9": "",
          "FMID__10": "South Carolina",
          "FMID__11": 29682,
          "FMID__12": "",
          "FMID__13": "",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -82.8187,
          "FMID__21": 34.8042,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "N",
          "SNAP": "N",
          "Organic": "-",
          "Bakedgoods": "",
          "Cheese": "",
          "Crafts": "",
          "Flowers": "",
          "Eggs": "",
          "Seafood": "",
          "Herbs": "",
          "Vegetables": "",
          "Honey": "",
          "Jams": "",
          "Maple": "",
          "Meat": "",
          "Nursery": "",
          "Nuts": "",
          "Plants": "",
          "Poultry": "",
          "Prepared": "",
          "Soap": "",
          "Trees": "",
          "Wine": "",
          "Coffee": "",
          "Beans": "",
          "Fruits": "",
          "Grains": "",
          "Juices": "",
          "Mushrooms": "",
          "PetFood": "",
          "Tofu": "",
          "WildHarvested": ""
        },
        {
          "FMID": 1010691,
          "FMID__1": "10th Steet Community Farmers Market",
          "FMID__2": "http://agrimissouri.com/mo-grown/grodetail.php?type=mo-grown&ID=275",
          "FMID__3": "",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "http://agrimissouri.com/mo-grown/grodetail.php?type=mo-grown&ID=275",
          "FMID__7": "10th Street and Poplar",
          "FMID__8": "Lamar",
          "FMID__9": "Barton",
          "FMID__10": "Missouri",
          "FMID__11": 64759,
          "FMID__12": "04/02/2014 to 11/30/2014",
          "FMID__13": "Wed: 3:00 PM-6:00 PM;Sat: 8:00 AM-1:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -94.2746191,
          "FMID__21": 37.495628,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "N",
          "SNAP": "N",
          "Organic": "-",
          "Bakedgoods": "Y",
          "Cheese": "N",
          "Crafts": "Y",
          "Flowers": "N",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "Y",
          "Poultry": "Y",
          "Prepared": "Y",
          "Soap": "Y",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1002454,
          "FMID__1": "112st Madison Avenue",
          "FMID__2": "Find us on Google!",
          "FMID__3": "",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "112th Madison Avenue",
          "FMID__8": "New York",
          "FMID__9": "New York",
          "FMID__10": "New York",
          "FMID__11": 10029,
          "FMID__12": "July to November",
          "FMID__13": "Tue:8:00 am - 5:00 pm;Sat:8:00 am - 8:00 pm;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -73.9493,
          "FMID__21": 40.7939,
          "Location": "Private business parking lot",
          "Credit": "N",
          "WIC": "N",
          "WICcash": "Y",
          "SFMNP": "Y",
          "SNAP": "N",
          "Organic": "-",
          "Bakedgoods": "Y",
          "Cheese": "N",
          "Crafts": "Y",
          "Flowers": "Y",
          "Eggs": "N",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "Y",
          "Plants": "N",
          "Poultry": "N",
          "Prepared": "Y",
          "Soap": "Y",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "N",
          "Fruits": "N",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1011100,
          "FMID__1": "12 South Farmers Market",
          "FMID__2": "http://www.12southfarmersmarket.com",
          "FMID__3": "12_South_Farmers_Market",
          "FMID__4": "@12southfrmsmkt",
          "FMID__5": "",
          "FMID__6": "@12southfrmsmkt",
          "FMID__7": "3000 Granny White Pike",
          "FMID__8": "Nashville",
          "FMID__9": "Davidson",
          "FMID__10": "Tennessee",
          "FMID__11": 37204,
          "FMID__12": "05/05/2015 to 10/27/2015",
          "FMID__13": "Tue: 3:30 PM-6:30 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -86.790709,
          "FMID__21": 36.11837,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "N",
          "SNAP": "Y",
          "Organic": "Y",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "N",
          "Flowers": "Y",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "Y",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "Y",
          "Prepared": "Y",
          "Soap": "Y",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "Y",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "Y",
          "Mushrooms": "Y",
          "PetFood": "Y",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1009845,
          "FMID__1": "125th Street Fresh Connect Farmers' Market",
          "FMID__2": "http://www.125thStreetFarmersMarket.com",
          "FMID__3": "https://www.facebook.com/125thStreetFarmersMarket",
          "FMID__4": "https://twitter.com/FarmMarket125th",
          "FMID__5": "",
          "FMID__6": "Instagram--> 125thStreetFarmersMarket",
          "FMID__7": "163 West 125th Street and Adam Clayton Powell, Jr. Blvd.",
          "FMID__8": "New York",
          "FMID__9": "New York",
          "FMID__10": "New York",
          "FMID__11": 10027,
          "FMID__12": "06/10/2014 to 11/25/2014",
          "FMID__13": "Tue: 10:00 AM-7:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -73.9482477,
          "FMID__21": 40.8089533,
          "Location": "Federal/State government building grounds",
          "Credit": "Y",
          "WIC": "Y",
          "WICcash": "N",
          "SFMNP": "Y",
          "SNAP": "Y",
          "Organic": "Y",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "Y",
          "Flowers": "Y",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "Y",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "Y",
          "Plants": "N",
          "Poultry": "Y",
          "Prepared": "Y",
          "Soap": "Y",
          "Trees": "N",
          "Wine": "Y",
          "Coffee": "Y",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "Y",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1005586,
          "FMID__1": "12th & Brandywine Urban Farm Market",
          "FMID__2": "https://www.facebook.com/pages/12th-Brandywine-Urban-Farm-Community-Garden/253769448091860",
          "FMID__3": "https://www.facebook.com/pages/12th-Brandywine-Urban-Farm-Community-Garden/253769448091860",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "https://www.facebook.com/delawareurbanfarmcoalition",
          "FMID__7": "12th & Brandywine Streets",
          "FMID__8": "Wilmington",
          "FMID__9": "New Castle",
          "FMID__10": "Delaware",
          "FMID__11": 19801,
          "FMID__12": "05/16/2014 to 10/17/2014",
          "FMID__13": "Fri: 8:00 AM-11:00 AM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -75.53446,
          "FMID__21": 39.742117,
          "Location": "On a farm from: a barn, a greenhouse, a tent, a stand, etc",
          "Credit": "N",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "N",
          "SNAP": "Y",
          "Organic": "N",
          "Bakedgoods": "N",
          "Cheese": "N",
          "Crafts": "N",
          "Flowers": "N",
          "Eggs": "N",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "N",
          "Jams": "N",
          "Maple": "N",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "N",
          "Prepared": "N",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1008071,
          "FMID__1": "14&U Farmers' Market",
          "FMID__2": "https://www.facebook.com/14UFarmersMarket",
          "FMID__3": "https://www.facebook.com/14UFarmersMarket",
          "FMID__4": "https://twitter.com/14UFarmersMkt",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "1400 U Street NW",
          "FMID__8": "Washington",
          "FMID__9": "District of Columbia",
          "FMID__10": "District of Columbia",
          "FMID__11": 20009,
          "FMID__12": "05/03/2014 to 11/22/2014",
          "FMID__13": "Sat: 9:00 AM-1:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -77.0320505,
          "FMID__21": 38.9169984,
          "Location": "Other",
          "Credit": "Y",
          "WIC": "Y",
          "WICcash": "Y",
          "SFMNP": "Y",
          "SNAP": "Y",
          "Organic": "Y",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "N",
          "Flowers": "Y",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "Y",
          "Plants": "Y",
          "Poultry": "Y",
          "Prepared": "N",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "Y",
          "Fruits": "Y",
          "Grains": "Y",
          "Juices": "Y",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1012710,
          "FMID__1": "14th & Kennedy Street Farmers Market",
          "FMID__2": "https://www.facebook.com/14KennnedyFarmersMarket/",
          "FMID__3": "https://www.facebook.com/14KennnedyFarmersMarket/",
          "FMID__4": "14KenFM",
          "FMID__5": "",
          "FMID__6": "instagram:14kenfm",
          "FMID__7": "5500 Colorado Avenue, NW",
          "FMID__8": "Washington",
          "FMID__9": "District of Columbia",
          "FMID__10": "District of Columbia",
          "FMID__11": 20011,
          "FMID__12": "04/09/2016 to 11/19/2016",
          "FMID__13": "Sat: 9:00 AM-1:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -77.0334486,
          "FMID__21": 38.9559783,
          "Location": "",
          "Credit": "Y",
          "WIC": "Y",
          "WICcash": "Y",
          "SFMNP": "Y",
          "SNAP": "Y",
          "Organic": "N",
          "Bakedgoods": "Y",
          "Cheese": "N",
          "Crafts": "Y",
          "Flowers": "Y",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "Y",
          "Prepared": "Y",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "Y",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "Y",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1019157,
          "FMID__1": "16th Ave Farmers Market",
          "FMID__2": "http://16thavefarmersmarket.com",
          "FMID__3": "",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "NE 16th Ave & Broadway",
          "FMID__8": "Portland",
          "FMID__9": "Multnomah",
          "FMID__10": "Oregon",
          "FMID__11": 97212,
          "FMID__12": "06/03/2018 to 10/28/2018",
          "FMID__13": "Sun: 9:00 AM-1:30 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -122.649446,
          "FMID__21": 45.534498,
          "Location": "",
          "Credit": "Y",
          "WIC": "Y",
          "WICcash": "Y",
          "SFMNP": "Y",
          "SNAP": "N",
          "Organic": "-",
          "Bakedgoods": "Y",
          "Cheese": "N",
          "Crafts": "Y",
          "Flowers": "Y",
          "Eggs": "N",
          "Seafood": "N",
          "Herbs": "N",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "Y",
          "Poultry": "N",
          "Prepared": "Y",
          "Soap": "Y",
          "Trees": "Y",
          "Wine": "N",
          "Coffee": "Y",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "Y"
        },
        {
          "FMID": 1018792,
          "FMID__1": "170 Farm Stand",
          "FMID__2": "https://www.facebook.com/CommunityFoodAction/",
          "FMID__3": "https://www.facebook.com/CommunityFoodAction/",
          "FMID__4": "https://twitter.com/GoodEatsBX",
          "FMID__5": "https://www.youtube.com/channel/UCZnt7sSNKIBrn2rMy1RyE_w",
          "FMID__6": "https://www.instagram.com/goodeatsbx/",
          "FMID__7": "NE Corner of 170th St. & Townsend Avenue",
          "FMID__8": "Bronx",
          "FMID__9": "Bronx",
          "FMID__10": "New York",
          "FMID__11": 10452,
          "FMID__12": "07/05/2017 to 11/22/2017",
          "FMID__13": "Wed: 2:30 PM-6:30 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -73.9167841,
          "FMID__21": 40.8398843,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "Y",
          "SFMNP": "Y",
          "SNAP": "Y",
          "Organic": "-",
          "Bakedgoods": "N",
          "Cheese": "N",
          "Crafts": "N",
          "Flowers": "N",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "N",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "N",
          "Maple": "N",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "N",
          "Prepared": "N",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "Y",
          "Fruits": "Y",
          "Grains": "Y",
          "Juices": "N",
          "Mushrooms": "Y",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1016782,
          "FMID__1": "175th Street Greenmarket",
          "FMID__2": "https://www.grownyc.org/greenmarket/manhattan/175th-street",
          "FMID__3": "https://www.facebook.com/ManhattanGreenmarkets/",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "175th Street between Wadsworth & Broadway",
          "FMID__8": "New York",
          "FMID__9": "New York",
          "FMID__10": "New York",
          "FMID__11": 10033,
          "FMID__12": "06/29/2017 to 11/22/2017",
          "FMID__13": "Tue: 8:00 AM-6:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -73.938049,
          "FMID__21": 40.846354,
          "Location": "",
          "Credit": "Y",
          "WIC": "Y",
          "WICcash": "Y",
          "SFMNP": "Y",
          "SNAP": "Y",
          "Organic": "N",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "N",
          "Flowers": "Y",
          "Eggs": "Y",
          "Seafood": "Y",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "N",
          "Prepared": "N",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "Y",
          "Juices": "Y",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1003877,
          "FMID__1": "17th Ave Market",
          "FMID__2": "http://www.iatp.org/minimarkets",
          "FMID__3": "",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "1622 6th St NE",
          "FMID__8": "Minneapolis",
          "FMID__9": "Hennepin",
          "FMID__10": "Minnesota",
          "FMID__11": 55413,
          "FMID__12": "June to September",
          "FMID__13": "Wed:3:00 pm - 7:00 pm;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -93.2591,
          "FMID__21": 45.0044,
          "Location": "Faith-based institution (e.g., church, mosque, synagogue, temple)",
          "Credit": "N",
          "WIC": "Y",
          "WICcash": "Y",
          "SFMNP": "Y",
          "SNAP": "N",
          "Organic": "-",
          "Bakedgoods": "N",
          "Cheese": "N",
          "Crafts": "N",
          "Flowers": "N",
          "Eggs": "N",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "N",
          "Honey": "N",
          "Jams": "N",
          "Maple": "N",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "N",
          "Prepared": "N",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "N",
          "Fruits": "N",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1016784,
          "FMID__1": "17th Street Farmers Market",
          "FMID__2": "http://enrichmond.org",
          "FMID__3": "https://www.facebook.com/17thStreetFarmersMarket/",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "100 North 17th St.",
          "FMID__8": "Richmond",
          "FMID__9": "Richmond City",
          "FMID__10": "Virginia",
          "FMID__11": 23219,
          "FMID__12": "06/08/2017 to",
          "FMID__13": "Thu: 3:00 PM-6:30 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -77.428364,
          "FMID__21": 37.53385,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "N",
          "SNAP": "Y",
          "Organic": "-",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "N",
          "Flowers": "N",
          "Eggs": "Y",
          "Seafood": "Y",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "Y",
          "Prepared": "N",
          "Soap": "Y",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "Y",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "Y",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1010968,
          "FMID__1": "18th and Christian Farmers' Market",
          "FMID__2": "http://thefoodtrust.org/farmers-markets/market/18th-Christian",
          "FMID__3": "",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "18th Street and Christian Street",
          "FMID__8": "Philadelphia",
          "FMID__9": "Philadelphia",
          "FMID__10": "Pennsylvania",
          "FMID__11": 19146,
          "FMID__12": "06/01/2015 to 11/15/2015",
          "FMID__13": "Thu: 3:00 PM-7:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -75.173431,
          "FMID__21": 39.940943,
          "Location": "",
          "Credit": "Y",
          "WIC": "Y",
          "WICcash": "N",
          "SFMNP": "Y",
          "SNAP": "Y",
          "Organic": "N",
          "Bakedgoods": "N",
          "Cheese": "N",
          "Crafts": "N",
          "Flowers": "N",
          "Eggs": "N",
          "Seafood": "N",
          "Herbs": "N",
          "Vegetables": "Y",
          "Honey": "N",
          "Jams": "N",
          "Maple": "N",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "N",
          "Poultry": "N",
          "Prepared": "N",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1009994,
          "FMID__1": "18th Street Farmer's Market",
          "FMID__2": "https://www.facebook.com/ScottsbluffFarmersMarket",
          "FMID__3": "https://www.facebook.com/ScottsbluffFarmersMarket",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "18th and Broadway",
          "FMID__8": "Scottsbluff",
          "FMID__9": "Scotts Bluff",
          "FMID__10": "Nebraska",
          "FMID__11": 69361,
          "FMID__12": "06/07/2014 to 09/27/2014",
          "FMID__13": "Sat: 8:00 AM-11:00 AM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -103.662538,
          "FMID__21": 41.864268,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "N",
          "SNAP": "N",
          "Organic": "Y",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "Y",
          "Flowers": "Y",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "N",
          "Maple": "N",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "Y",
          "Poultry": "Y",
          "Prepared": "Y",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "Y",
          "Beans": "Y",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1018365,
          "FMID__1": "18th Street Farmers Market",
          "FMID__2": "Find us on Google!",
          "FMID__3": "18th Street Farmers Market",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "825 18th Street",
          "FMID__8": "Charleston",
          "FMID__9": "Coles",
          "FMID__10": "Illinois",
          "FMID__11": 61920,
          "FMID__12": "05/20/2017 to 09/30/2017",
          "FMID__13": "Sat: 8:00 AM-12:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -88.1622392,
          "FMID__21": 39.4907144,
          "Location": "",
          "Credit": "Y",
          "WIC": "Y",
          "WICcash": "N",
          "SFMNP": "Y",
          "SNAP": "Y",
          "Organic": "-",
          "Bakedgoods": "Y",
          "Cheese": "N",
          "Crafts": "Y",
          "Flowers": "Y",
          "Eggs": "N",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "N",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "Y",
          "Poultry": "N",
          "Prepared": "N",
          "Soap": "Y",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "N",
          "Fruits": "Y",
          "Grains": "N",
          "Juices": "N",
          "Mushrooms": "N",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1012790,
          "FMID__1": "19/27 Community Farmers Market",
          "FMID__2": "https://www.facebook.com/1927-Community-Farmers-Market-1505265436358960/",
          "FMID__3": "https://www.facebook.com/1927-Community-Farmers-Market-1505265436358960/",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "NE 7th Ave",
          "FMID__8": "Chiefland",
          "FMID__9": "Levy",
          "FMID__10": "Florida",
          "FMID__11": 32626,
          "FMID__12": "09/03/2016 to 06/24/2017",
          "FMID__13": "Sat: 8:30 AM-1:00 PM;",
          "FMID__14": "09/02/2017 to 06/30/2018",
          "FMID__15": "Sat: 8:30 AM-1:00 PM;",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -82.8578732,
          "FMID__21": 29.4848541,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "N",
          "SNAP": "N",
          "Organic": "-",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "Y",
          "Flowers": "N",
          "Eggs": "Y",
          "Seafood": "N",
          "Herbs": "Y",
          "Vegetables": "Y",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "N",
          "Plants": "Y",
          "Poultry": "Y",
          "Prepared": "Y",
          "Soap": "Y",
          "Trees": "Y",
          "Wine": "N",
          "Coffee": "N",
          "Beans": "Y",
          "Fruits": "Y",
          "Grains": "Y",
          "Juices": "N",
          "Mushrooms": "Y",
          "PetFood": "Y",
          "Tofu": "N",
          "WildHarvested": "N"
        },
        {
          "FMID": 1012158,
          "FMID__1": "21 Acres Farm Market",
          "FMID__2": "http://21acres.org",
          "FMID__3": "https://www.facebook.com/21Acres/",
          "FMID__4": "@21acres",
          "FMID__5": "21AcresCenter's channel",
          "FMID__6": "Instagram @21acres",
          "FMID__7": "13701 NE 171st Street",
          "FMID__8": "Woodinville",
          "FMID__9": "King",
          "FMID__10": "Washington",
          "FMID__11": 98072,
          "FMID__12": "01/01/2016 to 12/31/2016",
          "FMID__13": "Wed: 11:00 AM-6:00 PM;Thu: 11:00 AM-6:00 PM;Fri: 11:00 AM-6:00 PM;Sat: 11:00 AM-6:00 PM;",
          "FMID__14": "",
          "FMID__15": "",
          "FMID__16": "",
          "FMID__17": "",
          "FMID__18": "",
          "FMID__19": "",
          "FMID__20": -122.1569875,
          "FMID__21": 47.7502397,
          "Location": "",
          "Credit": "Y",
          "WIC": "N",
          "WICcash": "N",
          "SFMNP": "N",
          "SNAP": "Y",
          "Organic": "Y",
          "Bakedgoods": "Y",
          "Cheese": "Y",
          "Crafts": "N",
          "Flowers": "N",
          "Eggs": "Y",
          "Seafood": "Y",
          "Herbs": "Y",
          "Vegetables": "N",
          "Honey": "Y",
          "Jams": "Y",
          "Maple": "N",
          "Meat": "Y",
          "Nursery": "N",
          "Nuts": "Y",
          "Plants": "N",
          "Poultry": "Y",
          "Prepared": "Y",
          "Soap": "N",
          "Trees": "N",
          "Wine": "N",
          "Coffee": "Y",
          "Beans": "Y",
          "Fruits": "Y",
          "Grains": "Y",
          "Juices": "Y",
          "Mushrooms": "Y",
          "PetFood": "N",
          "Tofu": "N",
          "WildHarvested": "N"
        },

        {
          "FMID__1": 1010968,
          "FMID__2": "18th and Christian Farmers' Market",
          "FMID__3": "http://thefoodtrust.org/farmers-markets/market/18th-Christian",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "18th Street and Christian Street",
          "FMID__9": "Philadelphia",
          "FMID__10": "Philadelphia",
          "FMID__11": "Pennsylvania",
          "FMID": 19146,
          "FMID": "06/01/2015 to 11/15/2015",
          "FMID__13": "Thu: 3:00 PM-7:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1009994,
          "FMID__2": "18th Street Farmer's Market",
          "FMID__3": "",
          "FMID__4": "https://www.facebook.com/ScottsbluffFarmersMarket",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "18th and Broadway",
          "FMID__9": "Scottsbluff",
          "FMID__10": "Scotts Bluff",
          "FMID__11": "Nebraska",
          "FMID": 69361,
          "FMID": "06/07/2014 to 09/27/2014",
          "FMID__13": "Sat: 8:00 AM-11:00 AM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1018365,
          "FMID__2": "18th Street Farmers Market",
          "FMID__3": "",
          "FMID__4": "18th Street Farmers Market",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "825 18th Street",
          "FMID__9": "Charleston ",
          "FMID__10": "Coles",
          "FMID__11": "Illinois",
          "FMID": 61920,
          "FMID": "05/20/2017 to 09/30/2017",
          "FMID__13": "Sat: 8:00 AM-12:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1012790,
          "FMID__2": "19/27 Community Farmers Market",
          "FMID__3": "",
          "FMID__4": "https://www.facebook.com/1927-Community-Farmers-Market-1505265436358960/",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "NE 7th Ave",
          "FMID__9": "Chiefland",
          "FMID__10": "Levy",
          "FMID__11": "Florida",
          "FMID": 32626,
          "FMID": "09/03/2016 to 06/24/2017",
          "FMID__13": "Sat: 8:30 AM-1:00 PM;",
          "FMID": "09/02/2017 to 06/30/2018",
          "FMID": "Sat: 8:30 AM-1:00 PM;"
        },
        {
          "FMID__1": 1012158,
          "FMID__2": "21 Acres Farm Market",
          "FMID__3": "http://21acres.org",
          "FMID__4": "https://www.facebook.com/21Acres/",
          "FMID__5": "@21acres",
          "FMID__6": "21AcresCenter's channel",
          "FMID__7": "Instagram @21acres",
          "FMID__8": "13701 NE 171st Street",
          "FMID__9": "Woodinville",
          "FMID__10": "King",
          "FMID__11": "Washington",
          "FMID": 98072,
          "FMID__13": "01/01/2016 to 12/31/2016",
          "FMID": "Wed: 11:00 AM-6:00 PM;Thu: 11:00 AM-6:00 PM;Fri: 11:00 AM-6:00 PM;Sat: 11:00 AM-6:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1010873,
          "FMID__2": "21st Street Farmers Market",
          "FMID__3": "Find us on Google!",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "SW 21st and Oakley",
          "FMID__9": "Topeka",
          "FMID__10": "Shawnee",
          "FMID__11": "Kansas",
          "FMID": 66604,
          "FMID": "06/05/2015 to 10/30/2015",
          "FMID__13": "Fri: 7:30 AM-12:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1005309,
          "FMID__2": "22nd and Tasker Farmers' Market",
          "FMID__3": "http://thefoodtrust.org/farmers-markets/market/22nd-tasker",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "22nd and Tasker Streets",
          "FMID__9": "Philadelphia",
          "FMID__10": "Philadelphia",
          "FMID__11": "Pennsylvania",
          "FMID": 19146,
          "FMID": "06/01/2015 to 11/01/2015",
          "FMID__13": "Tue: 2:00 PM-6:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1000709,
          "FMID__2": "22nd Annual Highlands Business Partnership Farmers Market",
          "FMID__3": "http://www.highlandsnj.com",
          "FMID__4": "https://www.facebook.com/pages/Highlands-Business-Partnership-Highlands-NJ/165486543524770",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "71 Waterwitch Avenue",
          "FMID__9": "Highlands",
          "FMID__10": "Monmouth",
          "FMID__11": "New Jersey",
          "FMID": 7732,
          "FMID": "06/25/2016 to 11/05/2016",
          "FMID__13": "Sat: 8:30 AM-2:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1011881,
          "FMID__2": "25th Street Market - North Logan at the Library Summer 2016",
          "FMID__3": "http://northloganmarket.com",
          "FMID__4": "25th Street Market - North Logan at the Library",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "Instagram: north logan market  (25th Street Market)",
          "FMID__8": "475 East 2500 North",
          "FMID__9": "North Logan",
          "FMID__10": "Cache",
          "FMID__11": "Utah",
          "FMID": 84341,
          "FMID": "05/07/2016 to 10/15/2016",
          "FMID__13": "Sun: 9:00 AM-1:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1010966,
          "FMID__2": "26th and Allegheny",
          "FMID__3": "http://thefoodtrust.org/farmers-markets/market/26th-Allegheny",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "26th Street and W Allegheny Avenue",
          "FMID__9": "Philadelphia",
          "FMID__10": "Philadelphia",
          "FMID__11": "Pennsylvania",
          "FMID": 19129,
          "FMID": "06/01/2015 to 11/15/2015",
          "FMID__13": "Wed: 1:00 PM-5:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1005299,
          "FMID__2": "29th and Wharton Farmers' Market",
          "FMID__3": "http://thefoodtrust.org/farmers-markets/market/29th-wharton",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "29th and Wharton Streets",
          "FMID__9": "Philadelphia",
          "FMID__10": "Philadelphia",
          "FMID__11": "Pennsylvania",
          "FMID": 19146,
          "FMID": "06/01/2015 to 11/15/2015",
          "FMID__13": "Tue: 2:00 PM-6:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1010994,
          "FMID__2": "2nd Street Farmers' Market",
          "FMID__3": "http://secondstageAmherst.org",
          "FMID__4": "second stage of AMherst",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "194 second street",
          "FMID__9": "Amherst",
          "FMID__10": "Amherst",
          "FMID__11": "Virginia",
          "FMID": 24521,
          "FMID": "05/05/2016 to 09/01/2016",
          "FMID__13": "Thu: 3:30 PM-6:30 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1009959,
          "FMID__2": "2nd Street Market - Five Rivers MetroPark",
          "FMID__3": "http://www.metroparks.org",
          "FMID__4": "https://www.facebook.com/2ndStreetMarket/",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "600 E. 2nd Street",
          "FMID__9": "Dayton",
          "FMID__10": "Montgomery",
          "FMID__11": "Ohio",
          "FMID": 45402,
          "FMID": "01/01/2018 to 05/31/2018",
          "FMID__13": "Thu: 11:00 AM-3:00 PM;Fri: 11:00 AM-3:00 PM;Sat: 8:00 AM-3:00 PM;",
          "FMID": "06/01/2018 to 12/31/2018",
          "FMID": "Thu: 11:00 AM-3:00 PM;Fri: 11:00 AM-3:00 PM;Sat: 8:00 AM-3:00 PM;Sun: 11:00 AM-3:00 PM;"
        },
        {
          "FMID__1": 1004950,
          "FMID__2": "3 French Hens French Country Market",
          "FMID__3": "http://www.3frenchhensmarket.blogspot.com",
          "FMID__4": "https://www.facebook.com/pages/3-French-Hens-French-Country-Market/422352511143508",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "123 W. Illinois ave. ",
          "FMID__9": "Morris",
          "FMID__10": "Grundy",
          "FMID__11": "Illinois",
          "FMID": 60450,
          "FMID": "05/12/2018 to 10/13/2018",
          "FMID__13": "Sat: 8:00 AM-2:00 PM;",
          "FMID": "11/09/2018 to 11/10/2018",
          "FMID": "Fri: 4:00 PM-10:00 PM;Sat: 10:00 AM-3:00 PM;"
        },
        {
          "FMID__1": 1010775,
          "FMID__2": "30A Farmers' Market",
          "FMID": "",
          "FMID__3": "https://www.facebook.com/30aFarmersMarket?ref=hl",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "Rosmary Beach Town Center",
          "FMID__9": "Rosemary Beach",
          "FMID__10": "Walton",
          "FMID__11": "Florida",
          "FMID": 32461,
          "FMID": "01/18/2015 to 01/05/2020",
          "FMID__13": "Sun: 9:00 AM-1:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1018656,
          "FMID__2": "31 & Main Farmers Market at Campus Town",
          "FMID__3": "http://www.31mainfarmersmarket.com",
          "FMID__4": "https://www.facebook.com/31mainfarmersmarket/",
          "FMID__5": "https://www.twitter.com/31mainfarmmarkt\t",
          "FMID__6": "",
          "FMID__7": "https://www.instagram.com/31mainfarmersmarket ",
          "FMID__8": "1928 Pennington Road",
          "FMID__9": "Ewing",
          "FMID__10": "Mercer",
          "FMID__11": "New Jersey",
          "FMID": 8618,
          "FMID": "06/11/2017 to 10/29/2017",
          "FMID__13": "Sun: 10:00 AM-2:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1005636,
          "FMID__2": "32nd Street/Waverly Farmers Market",
          "FMID__3": "http://www.32ndstreetmarket.org",
          "FMID__4": "https://www.facebook.com/pages/Baltimores-32nd-Street-Farmers-Market/194872083921466?sk=wall",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "E. 32nd & Barclay Street",
          "FMID__9": "Baltimore",
          "FMID__10": "Baltimore",
          "FMID__11": "Maryland",
          "FMID": 21218,
          "FMID": "01/01/2013 to 12/31/2013",
          "FMID__13": "Sat: 7:00 AM-12:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1005310,
          "FMID__2": "33rd and Diamond Farmers' Market",
          "FMID__3": "http://thefoodtrust.org/farmers-markets/market/33rd-diamond",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "N 33rd and Diamond Streets",
          "FMID__9": "Philadelphia",
          "FMID__10": "Philadelphia",
          "FMID__11": "Pennsylvania",
          "FMID": 19121,
          "FMID": "06/01/2015 to 11/01/2015",
          "FMID__13": "Thu: 2:00 PM-6:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1018389,
          "FMID__2": "38th & Meridian Farmer's Market ",
          "FMID__3": "Find us on Google!",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "3808 N Meridian St",
          "FMID__9": "Indianapolis",
          "FMID__10": "Marion",
          "FMID__11": "Indiana",
          "FMID": 46208,
          "FMID": "06/01/2017 to 09/21/2017",
          "FMID__13": "Thu: 4:00 PM-6:30 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1012280,
          "FMID__2": "39 North Marketplace",
          "FMID__3": "http://www.39northdowntown.com",
          "FMID__4": "39 North ",
          "FMID__5": "39North Downtown",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "Downtown Sparks Victorian Ave",
          "FMID__9": "Sparks",
          "FMID__10": "Washoe",
          "FMID__11": "Nevada",
          "FMID": 89431,
          "FMID": "06/09/2016 to 08/18/2016",
          "FMID__13": "Thu: 4:00 PM-9:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1011213,
          "FMID__2": "441 Ministries Farm Stand",
          "FMID__3": "Find us on Google!",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "441 Parsells Avenue",
          "FMID__9": "Rochester",
          "FMID__10": "Monroe",
          "FMID__11": "New York",
          "FMID": 14609,
          "FMID": "",
          "FMID__13": "Tue: 3:00 PM-7:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1010965,
          "FMID__2": "4th and Lehigh Farmers' Market",
          "FMID__3": "http://thefoodtrust.org/farmers-markets/market/fairhill-square",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "N 4th Street and W. Lehigh Avenue",
          "FMID__9": "Philadelphia",
          "FMID__10": "Philadelphia",
          "FMID__11": "Pennsylvania",
          "FMID": 19133,
          "FMID": "06/01/2015 to 11/22/2015",
          "FMID__13": "Tue: 1:00 PM-5:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1005304,
          "FMID__2": "52nd and Haverford Farmers' Market",
          "FMID__3": "http://thefoodtrust.org/farmers-markets/market/52nd-haverford",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "N 52nd Street and Haverford Avenue",
          "FMID__9": "Philadelphia",
          "FMID__10": "Philadelphia",
          "FMID__11": "Pennsylvania",
          "FMID": 19139,
          "FMID": "06/01/2015 to 11/15/2015",
          "FMID__13": "Wed: 1:00 PM-5:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1000060,
          "FMID__2": "57th Street Greenmarket",
          "FMID__3": "http://www.grownyc.org",
          "FMID__4": "https://www.facebook.com/ManhattanGreenmarkets",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "W 57 St. & 9 Ave",
          "FMID__9": "New York",
          "FMID__10": "New York",
          "FMID__11": "New York",
          "FMID": 10019,
          "FMID": "04/20/2013 to 12/21/2013",
          "FMID__13": "Wed: 8:00 AM-5:00 PM;Sat: 8:00 AM-5:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1005306,
          "FMID__2": "58th and Chester Farmers' Market",
          "FMID__3": "http://thefoodtrust.org/farmers-markets/market/58th-chester",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "58th Street and Chester Avenue",
          "FMID__9": "Philadelphia",
          "FMID__10": "Philadelphia",
          "FMID__11": "Pennsylvania",
          "FMID": 19143,
          "FMID": "06/01/2015 to 11/01/2015",
          "FMID__13": "Wed: 2:00 PM-6:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1018965,
          "FMID__2": "61st Street Farmers Market",
          "FMID__3": "https://experimentalstation.org/market",
          "FMID__4": "61market",
          "FMID__5": "61market",
          "FMID__6": "",
          "FMID__7": "Instagram: ",
          "FMID__8": "6100 S. Blackstone Ave",
          "FMID__9": "Chicago",
          "FMID__10": "Cook",
          "FMID__11": "Illinois",
          "FMID": 60637,
          "FMID": "05/12/2018 to 12/15/2018",
          "FMID__13": "Sat: 9:00 AM-2:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1000061,
          "FMID__2": "79th Street Greenmarket",
          "FMID__3": "http://www.grownyc.org",
          "FMID__4": "https://www.facebook.com/ManhattanGreenmarkets",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "Columbus - W 78 & 81 Sts.",
          "FMID__9": "New York",
          "FMID__10": "New York",
          "FMID__11": "New York",
          "FMID": 10024,
          "FMID": "01/01/2013 to 12/31/2013",
          "FMID__13": "Sun: 8:00 AM-5:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1000062,
          "FMID__2": "82nd Street Greenmarket",
          "FMID__3": "http://www.grownyc.org",
          "FMID__4": "https://www.facebook.com/ManhattanGreenmarkets",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "E 82nd St. - 1st & York Ave",
          "FMID__9": "New York",
          "FMID__10": "New York",
          "FMID__11": "New York",
          "FMID": 10028,
          "FMID": "01/01/2013 to 12/31/2013",
          "FMID__13": "Sat: 9:00 AM-2:30 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1008391,
          "FMID__2": "84 west farmers market (Dothan)",
          "FMID__3": "Find us on Google!",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "",
          "FMID__9": "Dothan",
          "FMID__10": "Houston",
          "FMID__11": "Alabama",
          "FMID": null,
          "FMID": "06/06/2013 to 08/08/2013",
          "FMID__13": "Thu: 3:00 PM-6:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1001961,
          "FMID__2": "8th Avenue City Farmers Market",
          "FMID__3": "Find us on Google!",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "8th Ave & 2nd St SE",
          "FMID__9": "Cedar Rapids",
          "FMID__10": "Linn",
          "FMID__11": "Iowa",
          "FMID": 52401,
          "FMID": "May to October",
          "FMID__13": "Tue:4:00 PM - 6:00 PM;Sat:7:30 AM - 12:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1000063,
          "FMID__2": "92nd Street Greenmarket",
          "FMID__3": "http://www.grownyc.org",
          "FMID__4": "https://www.facebook.com/ManhattanGreenmarkets",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "1st Ave - E 92nd & 93 Sts.",
          "FMID__9": "New York",
          "FMID__10": "New York",
          "FMID__11": "New York",
          "FMID": 10128,
          "FMID": "06/23/2013 to 11/24/2013",
          "FMID": "Sun: 9:00 AM-4:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1000064,
          "FMID__2": "97th Street Greenmarket",
          "FMID__3": "http://www.grownyc.org",
          "FMID__4": "https://www.facebook.com/ManhattanGreenmarkets",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "W 97 St. & Columbus",
          "FMID__9": "New York",
          "FMID__10": "New York",
          "FMID__11": "New York",
          "FMID": 10025,
          "FMID": "01/01/2013 to 12/31/2013",
          "FMID__13": "Fri: 8:00 AM-2:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1011989,
          "FMID__2": "9th and Grand Farmers Market",
          "FMID__3": "http://Farmtoforkks.com",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "304 West Grand Avenue",
          "FMID__9": "Salina",
          "FMID__10": "Saline",
          "FMID__11": "Kansas",
          "FMID": 67401,
          "FMID": "05/10/2016 to 09/27/2016",
          "FMID__13": "Tue: 4:00 PM-7:00 PM;",
          "FMID": "",
          "FMID": ""
        },
        {
          "FMID__1": 1000986,
          "FMID__2": "9th West Farmers Market/People's Market ",
          "FMID__3": "http://www.9thwestfarmersmarket.org",
          "FMID__4": "https://www.facebook.com/9thwestfarmersmarket",
          "FMID__5": "https://twitter.com/peoplesmarket",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "1060 South 900 West",
          "FMID__9": "SALT LAKE CITY",
          "FMID__10": "Salt Lake",
          "FMID__11": "Utah",
          "FMID": 84110,
          "FMID": "05/12/2013 to 10/20/2013",
          "FMID__13": "Sun: 9:00 AM-2:00 PM;",
          "FMID": "06/26/2016 to 08/01/2016",
          "FMID": ""
        },

        {
          "FMID__1": 1009004,
          "FMID__2": "A Growers' Market",
          "FMID__3": "Find us on Google!",
          "FMID__4": "",
          "FMID__5": "",
          "FMID__6": "",
          "FMID__7": "",
          "FMID__8": "229 Lake Ella Drive",
          "FMID__9": "Tallahassee ",
          "FMID__10": "Leon",
          "FMID__11": "Florida",
          "FMID": 32303,
          "FMID": "01/01/2018 to 12/31/2018",
          "FMID__13": "Wed: 12:00 PM-6:00 PM;Sat: 11:00 AM-3:00 PM;",
          "FMID": "",
          "FMID": ""
        }
      ]
 